jobs:
  miner:
    name: "Mineur"
    color: BLUE
    xp:
      break:
        coal_ore: 5
        copper_ore: 5
        iron_ore: 10
        gold_ore: 15
        lapis_ore: 20
        redstone_ore: 20
        emerald_ore: 30
        diamond_ore: 40
        nether_quartz_ore: 15
        nether_gold: 20
        ancient_debris: 50
    rewards:
      every_10_levels:
        item:
          - name: DIAMOND
            quantity: 1
      every_50_levels:
        item:
          - name: NETHERITE_INGOT
            quantity: 1
